version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
  frontend:
    image: "0rdinary/daeily-front"
    container_name: frontend
    ports:
      - "80:3000"